# Generated by Django 2.2.4 on 2022-06-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='admission_app.Course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(default='Empty', null=True, upload_to='cv_files/'),
        ),
    ]
