# Generated by Django 2.2.4 on 2022-06-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0002_auto_20220626_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(default=None, upload_to='course'),
            preserve_default=False,
        ),
    ]
