# Generated by Django 2.2.4 on 2022-06-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0004_auto_20220626_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(null=True, upload_to='course/'),
        ),
    ]
