# Generated by Django 2.2.4 on 2022-06-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0007_auto_20220627_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
