# Generated by Django 2.2.4 on 2022-06-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0010_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(null=True, upload_to='cv_files/'),
        ),
    ]
