# Generated by Django 2.2.4 on 2022-06-29 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0011_user_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(default='Empty', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='admission_app.Course'),
        ),
    ]
